Repository f-lab-edu/Picketing, pull requests merged in 2023-09, with the labels that each got.

#35 #21-Schedule-page-api
  app/src/main/java/com/picketing/www/business/domain/Schedule.java
  app/src/main/java/com/picketing/www/business/domain/schedule/DateSchedule.java
  app/src/main/java/com/picketing/www/business/domain/schedule/DateScheduleFactory.java
  app/src/main/java/com/picketing/www/business/domain/schedule/Schedule.java
  app/src/main/java/com/picketing/www/business/domain/schedule/ScheduleFactory.java
  app/src/main/java/com/picketing/www/business/domain/schedule/TimeSchedule.java
  app/src/main/java/com/picketing/www/business/domain/schedule/TimeScheduleFactory.java
  app/src/main/java/com/picketing/www/business/domain/schedule/YearAndMonthForShow.java
  app/src/main/java/com/picketing/www/business/service/schedule/ScheduleService.java
  app/src/main/java/com/picketing/www/business/service/user/UserService.java
  app/src/main/java/com/picketing/www/persistence/repository/schedule/ScheduleRepository.java
  app/src/main/java/com/picketing/www/persistence/table/schedule/DateSchedulePersist.java
  app/src/main/java/com/picketing/www/persistence/table/schedule/DateScheduleView.java
  app/src/main/java/com/picketing/www/persistence/table/schedule/TimeSchedulePersist.java
  app/src/main/java/com/picketing/www/presentation/controller/schedule/ScheduleController.java
  app/src/main/java/com/picketing/www/presentation/controller/user/UserController.java
  app/src/main/java/com/picketing/www/presentation/dto/request/schedule/ScheduleSearchRequest.java
  app/src/main/java/com/picketing/www/presentation/dto/response/schedule/ScheduleResponseDto.java
  app/src/test/java/com/picketing/www/presentation/controller/schedule/ScheduleControllerTest.java
Labels: feature

#54 [Feature] JPA로 변환
  app/build.gradle
  app/src/main/java/com/picketing/www/App.java
  app/src/main/java/com/picketing/www/business/domain/ShowFactory.java
  app/src/main/java/com/picketing/www/business/domain/UserFactory.java
  app/src/main/java/com/picketing/www/business/service/ShowService.java
  app/src/main/java/com/picketing/www/business/service/user/UserService.java
  app/src/main/java/com/picketing/www/persistence/repository/ShowRepository.java
  app/src/main/java/com/picketing/www/persistence/repository/UserRepository.java
  app/src/main/java/com/picketing/www/persistence/table/BaseEntity.java
  app/src/main/java/com/picketing/www/persistence/table/ShowPersist.java
  app/src/main/java/com/picketing/www/persistence/table/UserPersist.java
  app/src/main/resources/application-local.yml
  app/src/main/resources/application.yml
  app/src/test/java/com/picketing/www/presentation/controller/user/UserControllerTest.java
Labels: feature

#63 [Feature] 도메인 객체에 JPA 엔티티 적용: Show
  app/build.gradle
  app/src/main/java/com/picketing/www/business/domain/Show.java
  app/src/main/java/com/picketing/www/business/domain/ShowFactory.java
  app/src/main/java/com/picketing/www/business/domain/show/Show.java
  app/src/main/java/com/picketing/www/business/domain/show/ShowFactory.java
  app/src/main/java/com/picketing/www/business/service/ShowService.java
  app/src/main/java/com/picketing/www/business/service/show/ShowService.java
  app/src/main/java/com/picketing/www/persistence/repository/ShowRepository.java
  app/src/main/java/com/picketing/www/persistence/repository/show/ShowRepository.java
  app/src/main/java/com/picketing/www/persistence/table/UserPersist.java
  app/src/main/java/com/picketing/www/presentation/controller/show/ShowController.java
  app/src/main/java/com/picketing/www/presentation/dto/response/show/ShowDetailResponse.java
  app/src/main/resources/application-local.yml
  app/src/test/java/com/picketing/www/presentation/controller/show/ShowControllerTest.java
  app/src/test/resources/application.yml
Labels: 2

#57 [Feature]MySQL 설정을 위해 docker-compose 설정
  .env
  .github/CODEOWNERS
  Dockerfile
  app/build.gradle
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application-local.yml
  app/src/main/resources/application.yml
  app/src/main/resources/db.migration/V1.0__init_ddl.sql
  docker-compose.yml
Labels: feature

#69 [Feature] QueryDSL 적용
  app/build.gradle
  style/naver-checkstyle-rules.xml
  style/naver-checkstyle-suppressions.xml
  style/naver-intellij-formatter.xml
Labels: 0.5

#72 [Feature] 공연 좌석 가격 조회 API 설계
  app/src/main/java/com/picketing/www/business/domain/show/Show.java
  app/src/main/java/com/picketing/www/business/domain/show/seatgrade/Seat.java
  app/src/main/java/com/picketing/www/business/domain/show/seatgrade/SeatGrade.java
  app/src/main/java/com/picketing/www/business/service/show/ShowService.java
  app/src/main/java/com/picketing/www/presentation/controller/show/ShowController.java
  app/src/main/java/com/picketing/www/presentation/dto/response/show/ShowSeatPriceResponse.java
Labels: feature

#82 [Feature] 공연 예매 & 좌석 예매 도메인 설계
  app/src/main/java/com/picketing/www/business/domain/reservation/Reservation.java
  app/src/main/java/com/picketing/www/business/domain/reservation/ReservedSeat.java
Labels: feature
