Repository f-lab-edu/Picketing, pull requests merged in 2023-08, with the labels that each got.

#18 feat:#17: 공연 도메인, Persist 설계
  app/src/main/java/com/picketing/www/business/domain/Show.java
  app/src/main/java/com/picketing/www/business/type/AgeGroup.java
  app/src/main/java/com/picketing/www/business/type/Genre.java
  app/src/main/java/com/picketing/www/business/type/SubGenre.java
  app/src/main/java/com/picketing/www/persistence/table/ShowPersist.java
Labels: feature

#28 feat:#23: Github Actions를 이용한 CI 구축
  .github/workflows/gradle.yml
  app/build.gradle
Labels: feature

#30 feat:#15: ErrorCode 형식 변경 & Exception 수정
  app/src/main/java/com/picketing/www/application/advice/ControllerExceptionHandlerAdvice.java
  app/src/main/java/com/picketing/www/application/exception/BadRequestException.java
  app/src/main/java/com/picketing/www/application/exception/CustomException.java
  app/src/main/java/com/picketing/www/application/exception/ErrorCode.java
  app/src/main/java/com/picketing/www/application/exception/InvalidPasswordException.java
  app/src/main/java/com/picketing/www/application/exception/UserNotFoundException.java
  app/src/main/java/com/picketing/www/application/filter/encoding/PasswordEncodingFilter.java
  app/src/main/java/com/picketing/www/business/domain/User.java
  app/src/main/java/com/picketing/www/business/service/UserService.java
  app/src/main/java/com/picketing/www/presentation/dto/response/ErrorResponse.java
  app/src/test/java/com/picketing/www/business/domain/UserTest.java
Labels: feature

#32 feat:#31 code style check 룰 적용
  .github/workflows/gradle.yml
  style/naver-checkstyle-rules.xml
  style/naver-checkstyle-suppressions.xml
Labels: documentation, feature

#37 코드 스타일 정리
  app/src/main/java/com/picketing/www/application/advice/ControllerExceptionHandlerAdvice.java
  app/src/main/java/com/picketing/www/application/exception/CustomException.java
  app/src/main/java/com/picketing/www/application/exception/ErrorCode.java
  app/src/main/java/com/picketing/www/application/filter/encoding/PasswordEncodingFilter.java
  app/src/main/java/com/picketing/www/application/filter/encoding/password/HttpRequestWrapper.java
  app/src/main/java/com/picketing/www/application/filter/encoding/password/PasswordEncoder.java
  app/src/main/java/com/picketing/www/application/filter/encoding/password/PicketingServletInputStreamWrapper.java
  app/src/main/java/com/picketing/www/business/domain/Schedule.java
  app/src/main/java/com/picketing/www/business/domain/Show.java
  app/src/main/java/com/picketing/www/business/domain/User.java
  app/src/main/java/com/picketing/www/business/domain/UserFactory.java
  app/src/main/java/com/picketing/www/business/service/UserService.java
  app/src/main/java/com/picketing/www/business/type/AgeGroup.java
  app/src/main/java/com/picketing/www/business/type/Genre.java
  app/src/main/java/com/picketing/www/business/type/SubGenre.java
  app/src/main/java/com/picketing/www/persistence/repository/UserRepository.java
  app/src/main/java/com/picketing/www/persistence/table/SchedulePersist.java
  app/src/main/java/com/picketing/www/persistence/table/ShowPersist.java
  app/src/main/java/com/picketing/www/persistence/table/UserPersist.java
  app/src/main/java/com/picketing/www/presentation/controller/user/UserController.java
  app/src/main/java/com/picketing/www/presentation/dto/request/user/UserSignInRequest.java
  app/src/main/java/com/picketing/www/presentation/dto/response/ErrorResponse.java
  app/src/main/java/com/picketing/www/presentation/dto/response/user/UserSignInResponse.java
  app/src/test/java/com/picketing/www/business/domain/UserTest.java
Labels: refactor

#29 feat:#14: User api 테스트 작성
  app/build.gradle
  app/src/main/java/com/picketing/www/application/filter/encoding/PasswordEncodingFilter.java
  app/src/main/java/com/picketing/www/application/filter/encoding/password/PasswordEncodeConfig.java
  app/src/main/java/com/picketing/www/application/filter/encoding/password/PasswordEncoder.java
  app/src/main/java/com/picketing/www/business/domain/User.java
  app/src/main/java/com/picketing/www/business/service/UserService.java
  app/src/test/java/com/picketing/www/application/filter/encoding/PasswordEncodingFilterTest.java
  app/src/test/java/com/picketing/www/application/filter/encoding/password/PasswordEncoderTest.java
  app/src/test/java/com/picketing/www/business/domain/UserTest.java
  app/src/test/java/com/picketing/www/presentation/controller/user/UserControllerTest.java
Labels: test

#50 [Feature] User 도메인에도 id를 추가하며 관련 로직 수정
  app/src/main/java/com/picketing/www/application/interceptor/LoginCheckInterceptor.java
  app/src/main/java/com/picketing/www/business/domain/User.java
  app/src/main/java/com/picketing/www/business/domain/UserFactory.java
  app/src/main/java/com/picketing/www/business/service/UserService.java
  app/src/main/java/com/picketing/www/persistence/repository/UserRepository.java
  app/src/main/java/com/picketing/www/persistence/table/UserPersist.java
  app/src/test/java/com/picketing/www/application/interceptor/LoginCheckInterceptorTest.java
  app/src/test/java/com/picketing/www/presentation/controller/user/UserControllerTest.java
Labels: feature
